# Generated by Django 6.0.5 on 2026-05-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='x',
            field=models.TextField(default=''),
        ),
    ]
