# Generated by Django 6.0.5 on 2026-05-14 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_x'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='x',
        ),
    ]
